[build]
  publish = "dist"
  command = "yarn build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' do-shynet.bombarde32.net; connect-src 'self' do-shynet.bombarde32.net;"

[[plugins]]
    package = "netlify-plugin-11ty"
    [plugins.inputs]
        cache_img = './assets/img'
        cache_img_httpHeader = true
        cache_assets = '../.cache'
        # for other assets
        cache_other = []